#ifndef SCANNER_H
#define SCANNER_H

typedef enum ScannerToken {
	TOK_EOF = 0,
	TOK_ERROR = 256,

	/* Tipos, control, declaraciones, nativas, literales */
	TOK_KW_INT,
	TOK_KW_FLOAT,
	TOK_KW_DOUBLE,
	TOK_KW_CHAR,
	TOK_KW_STRING,
	TOK_KW_BOOL,
	TOK_KW_VOID,
	TOK_KW_IF,
	TOK_KW_ELSE,
	TOK_KW_WHILE,
	TOK_KW_FOR,
	TOK_KW_FOREACH,
	TOK_KW_IN,
	TOK_KW_RETURN,
	TOK_KW_BREAK,
	TOK_KW_CONTINUE,
	TOK_KW_VAR,
	TOK_KW_CONST,
	TOK_KW_DEF,
	TOK_KW_PRINT,
	TOK_KW_TRUE,
	TOK_KW_FALSE,

	/* Extras tematica quimica */
	TOK_KW_TABLA,
	TOK_KW_CAPTURA,
	TOK_KW_MIDE,
	TOK_KW_AVOGADRO,
	TOK_KW_DESDE,
	TOK_KW_HASTA,
	TOK_KW_ANALIZA,
	TOK_KW_MUESTRA,
	TOK_KW_BASE,
	TOK_KW_PRUEBA,
	TOK_KW_NEUTRALIZA,
	TOK_KW_EXPLOTA,
	TOK_KW_COMPUESTO,
	TOK_KW_NULO,
	TOK_IDENTIFIER,
	TOK_INT_LITERAL,
	TOK_FLOAT_LITERAL,
	TOK_STRING_LITERAL,
	TOK_CHAR_LITERAL,

	/* Aritmeticos */
	TOK_PLUS,
	TOK_MINUS,
	TOK_MULT,
	TOK_DIV,
	TOK_MOD,
	TOK_POW,

	/* Comparacion */
	TOK_EQ,
	TOK_NEQ,
	TOK_GTE,
	TOK_LTE,
	TOK_LT,
	TOK_GT,

	/* Logicos */
	TOK_AND_LOGIC,
	TOK_OR_LOGIC,
	TOK_NOT_LOGIC,

	/* Bitwise */
	TOK_AND_BIT,
	TOK_OR_BIT,
	TOK_NOT_BIT,
	TOK_SHIFT_LEFT,
	TOK_SHIFT_RIGHT,
	TOK_SHIFT_RIGHT_UNSIGNED,

	/* Asignacion */
	TOK_ASSIGN,
	TOK_PLUS_ASSIGN,
	TOK_MINUS_ASSIGN,
	TOK_MULT_ASSIGN,
	TOK_DIV_ASSIGN,
	TOK_MOD_ASSIGN,
	TOK_AND_ASSIGN,
	TOK_OR_ASSIGN,
	TOK_XOR_ASSIGN,
	TOK_SHL_ASSIGN,
	TOK_SHR_ASSIGN,
	TOK_SHRU_ASSIGN,

	/* Incremento / Decremento / Flecha */
	TOK_INCREMENT,
	TOK_DECREMENT,
	TOK_ARROW,
	TOK_REVERSIBLE,
	TOK_FAT_ARROW,
	TOK_QUESTION,

	/* Palabras reservadas para operadores */
	TOK_MAS,
	TOK_MENOS,
	TOK_POR,
	TOK_ENTRE,
	TOK_ELEVA,
	TOK_RAIZ,
	TOK_RESIDUO_MOD,
	TOK_EQUILIBRA,
	TOK_DESEQUILIBRA,
	TOK_MAYOR_IGUAL,
	TOK_MENOR_IGUAL,
	TOK_MAYOR,
	TOK_MENOR,
	TOK_UNIDO,
	TOK_MEZCLA,
	TOK_INVIERTE,
	TOK_ENLACE_BITS,
	TOK_MEZCLA_BITS,
	TOK_INTERCAMBIA,
	TOK_INVIERTE_BITS,
	TOK_IZQUIERDA,
	TOK_DERECHA_SIN_SIGNO,
	TOK_DERECHA,

	/* Delimitadores */
	TOK_LPAREN,
	TOK_RPAREN,
	TOK_LBRACKET,
	TOK_RBRACKET,
	TOK_LBRACE,
	TOK_RBRACE,
	TOK_COMMA,
	TOK_SEMICOLON,
	TOK_DOT,
	TOK_COLON
} ScannerToken;

const char *scanner_token_name(int token);

#endif // SCANNER_H
